name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release --DSDL_UNIX_CONSOLE_BUILD=ON

      - name: Build Tests and Emulator Core
        run: cmake --build build --target emulate-game-boy-tests -- -j$(nproc)

      - name: Run Tests
        run: ctest --test-dir build --parallel $(nproc) --output-on-failure
